USE DEMO1

CREATE TABLE DEPT( 
DEPARTMENTID INT PRIMARY KEY, 
DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE, 
DEPARTMENTCODE VARCHAR(50) NOT NULL UNIQUE, 
LOCATION VARCHAR(50) NOT NULL) 
 
INSERT INTO DEPT VALUES(1,'ADMIN','ADM','A-BLOCK') 
INSERT INTO DEPT VALUES(2,'COMPUTER','CE','C-BLOCK') 
INSERT INTO DEPT VALUES(3,'CIVIL','CI','G-BLOCK') 
INSERT INTO DEPT VALUES(4,'ELECTRICAL','EE','E-BLOCK') 
INSERT INTO DEPT VALUES(5,'MECHANICAL','ME','B-BLOCK')

SELECT * FROM DEPT

CREATE TABLE PERSON( 
PERSONID INT PRIMARY KEY, 
PERSONNAME VARCHAR(100) NOT NULL, 
DEPARTMENTID INT NULL FOREIGN KEY REFERENCES DEPT(DEPARTMENTID), 
SALARY DECIMAL(8,2) NOT NULL, 
JOININGDATE DATETIME NOT NULL, 
CITY VARCHAR(100) NOT NULL) 
 
INSERT INTO PERSON VALUES(101,'RAHUL TRIPATHI',2,56000,'01-01-2000','RAJKOT') 
INSERT INTO PERSON VALUES(102,'HARDIK PANDYA',3,18000,'25-SEP-2001','AHMEDABAD') 
INSERT INTO PERSON VALUES(103,'BHAVIN KANANI',4,25000,'14-MAY-2000','BARODA') 
INSERT INTO PERSON VALUES(104,'BHOOMI VAISHNAV',1,39000,'08-FEB-2005','RAJKOT') 
INSERT INTO PERSON VALUES(105,'ROHIT TOPIYA',2,17000,'23-JUL-2001','JAMNAGAR') 
INSERT INTO PERSON VALUES(106,'PRIYA MENPARA',NULL,9000,'18-OCT-2000','AHMEDABAD') 
INSERT INTO PERSON VALUES(107,'NEHA SHARMA',2,34000,'25-DEC-2002','RAJKOT') 
INSERT INTO PERSON VALUES(108,'NAYAN GOSWAMI',3,25000,'01-JUL-2001','RAJKOT') 
INSERT INTO PERSON VALUES(109,'MEHUL BHUNDIYA',4,13500,'09-JAN-2005','BARODA') 
INSERT INTO PERSON VALUES(110,'MOHIT MARU',5,14000,'25-MAY-2000','JAMNAGAR') 
 
SELECT * FROM DEPT 
SELECT * FROM PERSON 


-------TYPES OF JOIN------ 

---31 INNER JOIN--- 
SELECT  
 PERSON.PERSONNAME, 
 DEPT.DEPARTMENTNAME 
FROM PERSON  
INNER JOIN DEPT  
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID 
 
 ---32 LEFT OUTER JOIN---- 
SELECT  
 PERSON.PERSONNAME, 
 DEPT.DEPARTMENTNAME 
FROM PERSON  
LEFT OUTER JOIN DEPT  
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID 
 ---33 RIGHT OUTER JOIN---- 
SELECT  
 PERSON.PERSONNAME, 
 DEPT.DEPARTMENTNAME 
FROM PERSON  
RIGHT OUTER JOIN DEPT  
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID 

---34 FULL OUTER JOIN---- 
SELECT  
 PERSON.PERSONNAME, 
 DEPT.DEPARTMENTNAME 
FROM PERSON
FULL OUTER JOIN DEPT  
ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID 


---35 CROSS JOIN---- 
SELECT * 
FROM PERSON  
CROSS JOIN  
DEPT --OR 
SELECT * 
FROM PERSON, DEPT 
 
 ---SELF JOIN--- 
CREATE TABLE Employe( 
EmpNo   VARCHAR(6)     PRIMARY KEY, 
Name    VARCHAR(50)    NOT NULL, 
MngrNo  VARCHAR(6)     NULL) 
 
INSERT INTO Employe (EmpNo, Name, MngrNo) VALUES 
  ('E00004', 'Milan',   NULL), 
  ('E00005', 'Jay',     NULL), 
  ('E00002', 'Rohan',   'E00005'), 
  ('E00003', 'Priya',   'E00005'), 
  ('E00001', 'Tarun',   'E00002'), 
  ('E00006', 'Anjana',  'E00003'); 
 
  SELECT * FROM Employe 
 --36 TO RETRIEVE THE LIST OF EMPLOYEES NAME AND THEIR MANAGERS NAME 
SELECT 
 E.NAME AS EMPLOYE, 
 M.NAME AS MANAGER 
FROM EMPLOYE E 
INNER JOIN EMPLOYE M 
ON E.MNGRNO=M.EMPNO 
 
 
 -------------------3 TABLES JOIN-------------- --  AUTHORS TABLE 
CREATE TABLE AUTHORS ( 
    AUTHORID INT PRIMARY KEY, 
    AUTHORNAME VARCHAR(100), 
    BIRTHDATE DATE 
); 
INSERT INTO AUTHORS (AUTHORID, AUTHORNAME, BIRTHDATE) 
VALUES 
(1, 'RABINDRANATH TAGORE', '1861-05-07'), 
(2, 'CHETAN BHAGAT', '1974-04-22'), 
(3, 'ARUNDHATI ROY', '1961-11-24'); 